import "dotenv/config";import { prisma } from "../lib/prisma";import { getAppToken } from "../lib/twitch";import { floorHour } from "../lib/time";
const args=Object.fromEntries(process.argv.slice(2).reduce((a,c,i,arr)=>c.startsWith("--")?[...a,[c.slice(2),arr[i+1]]]:a,[] as [string,string][]));
async function main(){const language=args.language??process.env.TWITCH_DEFAULT_LANGUAGE??"all";const pages=Number(args.pages??process.env.TWITCH_COLLECT_MAX_PAGES??10);const token=await getAppToken();const cid=process.env.TWITCH_CLIENT_ID!;let cursor="";let fetched=0;const seen=new Set<string>();const agg=new Map<string,{game_name:string;viewer:number;streams:number;peak:number}>();
for(let p=0;p<pages;p++){const u=new URL("https://api.twitch.tv/helix/streams");u.searchParams.set("first","100");u.searchParams.set("type","live");if(language!=="all")u.searchParams.set("language",language);if(cursor)u.searchParams.set("after",cursor);const r=await fetch(u,{headers:{"Client-Id":cid,Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(String(r.status));const j:any=await r.json();for(const s of j.data){fetched++;if(seen.has(s.id)||!s.game_id)continue;seen.add(s.id);const e=agg.get(s.game_id)??{game_name:s.game_name,viewer:0,streams:0,peak:0};e.viewer+=s.viewer_count;e.streams++;e.peak=Math.max(e.peak,s.viewer_count);agg.set(s.game_id,e);}cursor=j.pagination?.cursor;if(!cursor)break;}
const capturedAt=new Date();const capturedHour=floorHour(capturedAt);const snapshot=await prisma.snapshot.upsert({where:{capturedHourUtc_language_source:{capturedHourUtc:capturedHour,language,source:"helix_streams"}},update:{fetchedStreamCount:fetched,uniqueStreamCount:seen.size,aggregatedGameCount:agg.size,maxPages:pages,capturedAtUtc:capturedAt},create:{capturedAtUtc:capturedAt,capturedHourUtc:capturedHour,language,source:"helix_streams",maxPages:pages,fetchedStreamCount:fetched,uniqueStreamCount:seen.size,aggregatedGameCount:agg.size}});
const ordered=[...agg.entries()].sort((a,b)=>b[1].viewer-a[1].viewer);
for(const [i,[gid,v]] of ordered.entries()){const game=await prisma.game.upsert({where:{twitchGameId:gid},update:{name:v.game_name,lastSeenAt:capturedAt},create:{twitchGameId:gid,name:v.game_name,firstSeenAt:capturedAt,lastSeenAt:capturedAt}});await prisma.gameSnapshotMetric.upsert({where:{snapshotId_gameId:{snapshotId:snapshot.id,gameId:game.id}},update:{rank:i+1,viewerCount:v.viewer,streamCount:v.streams,sampledStreamCount:v.streams,peakStreamViewerCount:v.peak},create:{snapshotId:snapshot.id,gameId:game.id,rank:i+1,viewerCount:v.viewer,streamCount:v.streams,sampledStreamCount:v.streams,peakStreamViewerCount:v.peak}})}
console.log({capturedAt,language,fetchedStreamCount:fetched,uniqueStreamCount:seen.size,aggregatedGameCount:agg.size,savedMetricsCount:ordered.length});}
main().finally(()=>prisma.$disconnect());
